---
 - name: playbook2
   hosts: ansible
   become: true
   gather_facts: yes
   vars:
      services:
         - httpd
         - nfs-utils
   tasks:
     - name: copy file  
       copy:   
           src: /var/lib/jenkins/workspace/ansibleservicecheck/index.html
           dest: /var/www/html/
           mode: 777
     - name : user create new
       user:
         name: mohit246756
         home: /home/mohittalwar456756
         shell: /bin/bash
         comment: new 2
         state: present
     - name: debug users
       debug:
          var: ansible_facts['ansible_default_ipv4']
     - name: ping check
       ping: 
     - name: debug response
       debug: 
         msg: "error 45 msg"
     - name: service install 
       dnf:
          name: "{{ services }}"
          state: latest
     - name: check service
       service: 
         name: "{{ services }}"
         state: present
       notify: 
          - service-restart   
   handlers:
      - name: service-restart
        ansible.builtin.service: 
          name: "{{ item | splitext | first }}" 
          state: started
          enabled: yes
        with_items:
            - httpd
            - nfs-server

            
